# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logoutConfirm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(289, 249)
        Dialog.setStyleSheet("*{\n"
"border: none;\n"
"background-color: transparent;\n"
"background: transparent;\n"
"padding: 0;\n"
"margin: 0;\n"
"color: #fff\n"
"}\n"
"#widget,#widget_4{\n"
"border-image: url(:/images/back1.png);\n"
"border-radius: 20px;\n"
"}\n"
"#widget_2,#widget_7{\n"
"background-color:rgba(0,0,0,175);\n"
"border-radius: 20px;\n"
"}")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.page)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.widget_3.setFont(font)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.stud = QtWidgets.QWidget(self.widget_2)
        self.stud.setObjectName("stud")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.stud)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.yes_Button = QtWidgets.QPushButton(self.stud)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.yes_Button.setFont(font)
        self.yes_Button.setStyleSheet("#yes_Button{\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"padding-right:10px;\n"
"}\n"
"#yes_Button:hover{\n"
"    background-color: rgb(39, 94, 35);\n"
"border-radius: 5px;\n"
"}\n"
"#yes_Button:pressed{\n"
"    background-color: rgb(7, 75, 0);\n"
"border-radius: 5px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/greenIcons/greenColorIcons/check.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.yes_Button.setIcon(icon)
        self.yes_Button.setIconSize(QtCore.QSize(40, 40))
        self.yes_Button.setObjectName("yes_Button")
        self.horizontalLayout.addWidget(self.yes_Button, 0, QtCore.Qt.AlignHCenter)
        self.no_Button = QtWidgets.QPushButton(self.stud)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.no_Button.setFont(font)
        self.no_Button.setStyleSheet("#no_Button{\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"padding-right:10px;\n"
"}\n"
"#no_Button:hover{\n"
"    background-color: rgb(217, 162, 162);\n"
"border-radius: 5px;\n"
"}\n"
"#no_Button:pressed{\n"
"background-color: rgb(61, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/redIcons/redColorIcons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.no_Button.setIcon(icon1)
        self.no_Button.setIconSize(QtCore.QSize(40, 40))
        self.no_Button.setObjectName("no_Button")
        self.horizontalLayout.addWidget(self.no_Button, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.stud)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.widget)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_4 = QtWidgets.QWidget(self.page_2)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_7 = QtWidgets.QWidget(self.widget_4)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_8 = QtWidgets.QWidget(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.widget_8.setFont(font)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_10.addWidget(self.label_3)
        self.verticalLayout_9.addWidget(self.widget_8)
        self.teach = QtWidgets.QWidget(self.widget_7)
        self.teach.setObjectName("teach")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.teach)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.yes_Button_3 = QtWidgets.QPushButton(self.teach)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.yes_Button_3.setFont(font)
        self.yes_Button_3.setStyleSheet("#yes_Button_3{\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"padding-right:10px;\n"
"}\n"
"#yes_Button_3:hover{\n"
"    background-color: rgb(39, 94, 35);\n"
"border-radius: 5px;\n"
"}\n"
"#yes_Button_3:pressed{\n"
"    background-color: rgb(7, 75, 0);\n"
"border-radius: 5px;\n"
"}")
        self.yes_Button_3.setIcon(icon)
        self.yes_Button_3.setIconSize(QtCore.QSize(40, 40))
        self.yes_Button_3.setObjectName("yes_Button_3")
        self.horizontalLayout_3.addWidget(self.yes_Button_3, 0, QtCore.Qt.AlignHCenter)
        self.no_Button_3 = QtWidgets.QPushButton(self.teach)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.no_Button_3.setFont(font)
        self.no_Button_3.setStyleSheet("#no_Button_3{\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"padding-right:10px;\n"
"}\n"
"#no_Button_3:hover{\n"
"    background-color: rgb(217, 162, 162);\n"
"border-radius: 5px;\n"
"}\n"
"#no_Button_3:pressed{\n"
"background-color: rgb(61, 0, 0);\n"
"border-radius: 5px;\n"
"}")
        self.no_Button_3.setIcon(icon1)
        self.no_Button_3.setIconSize(QtCore.QSize(40, 40))
        self.no_Button_3.setObjectName("no_Button_3")
        self.horizontalLayout_3.addWidget(self.no_Button_3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_9.addWidget(self.teach)
        self.verticalLayout_8.addWidget(self.widget_7)
        self.verticalLayout_11.addWidget(self.widget_4)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_12.addWidget(self.stackedWidget)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Are you sure you want to \n"
"Log Out of this Account?"))
        self.yes_Button.setText(_translate("Dialog", "Yes"))
        self.no_Button.setText(_translate("Dialog", "No"))
        self.label_3.setText(_translate("Dialog", "Are you sure you want to \n"
"Log Out of this Account?"))
        self.yes_Button_3.setText(_translate("Dialog", "Yes"))
        self.no_Button_3.setText(_translate("Dialog", "No"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
