# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'studRegister.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, res

# class that  will change ,self.widget = QtWidgets.QWidget(Form), into moWidget
# this class will used to move the frameless form Window
class moWidget (QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(moWidget, self).__init__(parent)
        self.parent = parent
    def mousePressEvent(self, event):
        if event.button() == QtCore.Qt.LeftButton:
                self.dragPosition = event.globalPos() - self.parent.frameGeometry().topLeft()
                event.accept()
    def mouseMoveEvent(self, event):
        if event.buttons() == QtCore.Qt.LeftButton:
                self.parent.move(event.globalPos() - self.dragPosition)
                event.accept()

class Ui_studRegisterWindow(object):
    def setupUi(self, studRegisterWindow):
        studRegisterWindow.setObjectName("studRegisterWindow")
        studRegisterWindow.resize(587, 685)
        studRegisterWindow.setFixedSize(587, 685)
        # to remove close,minimize,maximize button
        studRegisterWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        # to remove the constant background of the app
        studRegisterWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(studRegisterWindow.sizePolicy().hasHeightForWidth())
        studRegisterWindow.setSizePolicy(sizePolicy)
        studRegisterWindow.setMinimumSize(QtCore.QSize(306, 597))
        
        self.centralwidget = moWidget(studRegisterWindow)
        
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 40, 300, 571))
        self.label.setStyleSheet("border-image: url(:/images/back1.png);\n"
"border-radius: 20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(159, 50, 281, 551))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.835227 rgba(0, 0, 0, 75));\n"
"border-radius: 20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 60, 280, 531))
        self.label_3.setStyleSheet("background-color:rgba(0,0,0,150);\n"
"border-radius:15px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(220, 70, 141, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgba(255, 255, 255,210);\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(210, 120, 161, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgba(255, 255, 255,210);\n"
"")
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setIndent(-1)
        self.label_6.setObjectName("label_6")
        self.studBackToMain_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.studBackToMain_pushButton.setGeometry(QtCore.QRect(350, 500, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.studBackToMain_pushButton.setFont(font)
        self.studBackToMain_pushButton.setStyleSheet("QPushButton#studBackToMain_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba();\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#studBackToMain_pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#studBackToMain_pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200)\n"
"}\n"
"")
        self.studBackToMain_pushButton.setObjectName("studBackToMain_pushButton")
        self.studEmail_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.studEmail_lineEdit.setGeometry(QtCore.QRect(200, 370, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.studEmail_lineEdit.setFont(font)
        self.studEmail_lineEdit.setAutoFillBackground(False)
        self.studEmail_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.studEmail_lineEdit.setText("")
        self.studEmail_lineEdit.setObjectName("studEmail_lineEdit")
        self.studLastName_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.studLastName_lineEdit.setGeometry(QtCore.QRect(200, 220, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.studLastName_lineEdit.setFont(font)
        self.studLastName_lineEdit.setAutoFillBackground(False)
        self.studLastName_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.studLastName_lineEdit.setText("")
        self.studLastName_lineEdit.setObjectName("studLastName_lineEdit")
        self.studMiddleInit_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.studMiddleInit_lineEdit.setGeometry(QtCore.QRect(340, 170, 61, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.studMiddleInit_lineEdit.setFont(font)
        self.studMiddleInit_lineEdit.setAutoFillBackground(False)
        self.studMiddleInit_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.studMiddleInit_lineEdit.setText("")
        self.studMiddleInit_lineEdit.setObjectName("studMiddleInit_lineEdit")
        self.studFirstName_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.studFirstName_lineEdit.setGeometry(QtCore.QRect(200, 170, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.studFirstName_lineEdit.setFont(font)
        self.studFirstName_lineEdit.setAutoFillBackground(False)
        self.studFirstName_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.studFirstName_lineEdit.setText("")
        self.studFirstName_lineEdit.setObjectName("studFirstName_lineEdit")
        self.studPass_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.studPass_lineEdit.setGeometry(QtCore.QRect(200, 420, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.studPass_lineEdit.setFont(font)
        self.studPass_lineEdit.setAutoFillBackground(False)
        self.studPass_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.studPass_lineEdit.setText("")
        self.studPass_lineEdit.setObjectName("studPass_lineEdit")
        self.studSchool_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.studSchool_lineEdit.setGeometry(QtCore.QRect(200, 320, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.studSchool_lineEdit.setFont(font)
        self.studSchool_lineEdit.setAutoFillBackground(False)
        self.studSchool_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.studSchool_lineEdit.setText("")
        self.studSchool_lineEdit.setObjectName("studSchool_lineEdit")
        self.studRegister_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.studRegister_pushButton.setGeometry(QtCore.QRect(200, 500, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.studRegister_pushButton.setFont(font)
        self.studRegister_pushButton.setStyleSheet("QPushButton#studRegister_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba();\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#studRegister_pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#studRegister_pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200)\n"
"}\n"
"")
        self.studRegister_pushButton.setObjectName("studRegister_pushButton")
        self.studYrSec_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.studYrSec_lineEdit.setGeometry(QtCore.QRect(200, 270, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.studYrSec_lineEdit.setFont(font)
        self.studYrSec_lineEdit.setAutoFillBackground(False)
        self.studYrSec_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.studYrSec_lineEdit.setText("")
        self.studYrSec_lineEdit.setObjectName("studYrSec_lineEdit")
        self.studToLogIn_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.studToLogIn_pushButton.setGeometry(QtCore.QRect(210, 550, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.studToLogIn_pushButton.setFont(font)
        self.studToLogIn_pushButton.setStyleSheet("QPushButton#studToLogIn_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,140)\n"
"}\n"
"QPushButton#studToLogIn_pushButton:pressed{\n"
"    color: rgba(251, 153, 93, 1);\n"
"}\n"
"")
        self.studToLogIn_pushButton.setAutoDefault(False)
        self.studToLogIn_pushButton.setDefault(False)
        self.studToLogIn_pushButton.setFlat(True)
        self.studToLogIn_pushButton.setObjectName("studToLogIn_pushButton")
        self.exitProgram_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitProgram_pushButton.setGeometry(QtCore.QRect(410, 50, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.exitProgram_pushButton.setFont(font)
        self.exitProgram_pushButton.setStyleSheet("QPushButton#exitProgram_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba();\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#exitProgram_pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#exitProgram_pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200)\n"
"}\n"
"")
        self.exitProgram_pushButton.setObjectName("exitProgram_pushButton")
        studRegisterWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(studRegisterWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 587, 21))
        self.menubar.setObjectName("menubar")
        studRegisterWindow.setMenuBar(self.menubar)
        
        self.label.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0, color=QtGui.QColor(234, 221, 186, 100)))
        self.label_3.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0, color=QtGui.QColor(105, 118, 132, 100)))
        self.studRegister_pushButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=3, yOffset=3, color=QtGui.QColor(105, 118, 132, 100)))
        self.studBackToMain_pushButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=3, yOffset=3, color=QtGui.QColor(105, 118, 132, 100)))

        self.retranslateUi(studRegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(studRegisterWindow)

        self.studRegister_pushButton.clicked.connect(studRegisterWindow.toRegisterDb)
        self.studToLogIn_pushButton.clicked.connect(studRegisterWindow.goBack)
        self.studBackToMain_pushButton.clicked.connect(studRegisterWindow.goBack)
        self.exitProgram_pushButton.clicked.connect(studRegisterWindow.toExitProg)

    def retranslateUi(self, studRegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        studRegisterWindow.setWindowTitle(_translate("studRegisterWindow", "MainWindow"))
        self.label_5.setText(_translate("studRegisterWindow", "Mathguro"))
        self.label_6.setText(_translate("studRegisterWindow", "Student\'s Register"))
        self.studBackToMain_pushButton.setText(_translate("studRegisterWindow", "Back"))
        self.studEmail_lineEdit.setPlaceholderText(_translate("studRegisterWindow", " Email:"))
        self.studLastName_lineEdit.setPlaceholderText(_translate("studRegisterWindow", "Last Name:"))
        self.studMiddleInit_lineEdit.setPlaceholderText(_translate("studRegisterWindow", "M.I:"))
        self.studFirstName_lineEdit.setPlaceholderText(_translate("studRegisterWindow", "First Name:"))
        self.studPass_lineEdit.setPlaceholderText(_translate("studRegisterWindow", " Password:"))
        self.studSchool_lineEdit.setPlaceholderText(_translate("studRegisterWindow", " School:"))
        self.studRegister_pushButton.setText(_translate("studRegisterWindow", "Register"))
        self.studYrSec_lineEdit.setPlaceholderText(_translate("studRegisterWindow", " Year & Section:"))
        self.studToLogIn_pushButton.setText(_translate("studRegisterWindow", "Already have an Account? Log In Here"))
        self.exitProgram_pushButton.setText(_translate("studRegisterWindow", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studRegisterWindow = QtWidgets.QMainWindow()
    ui = Ui_studRegisterWindow()
    ui.setupUi(studRegisterWindow)
    studRegisterWindow.show()
    sys.exit(app.exec_())
