# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'studLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, res

# class that  will change ,self.widget = QtWidgets.QWidget(Form), into moWidget
# this class will used to move the frameless form Window
class moWidget (QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(moWidget, self).__init__(parent)
        self.parent = parent
    def mousePressEvent(self, event):
        if event.button() == QtCore.Qt.LeftButton:
                self.dragPosition = event.globalPos() - self.parent.frameGeometry().topLeft()
                event.accept()
    def mouseMoveEvent(self, event):
        if event.buttons() == QtCore.Qt.LeftButton:
                self.parent.move(event.globalPos() - self.dragPosition)
                event.accept()

class Ui_studLoginWindow(object):
    def setupUi(self, studLoginWindow):
        studLoginWindow.setObjectName("studLoginWindow")
        studLoginWindow.resize(447, 572)
        studLoginWindow.setFixedSize(447, 572)
        # to remove close,minimize,maximize button
        studLoginWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        # to remove the constant background of the app
        studLoginWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(studLoginWindow.sizePolicy().hasHeightForWidth())
        studLoginWindow.setSizePolicy(sizePolicy)
        studLoginWindow.setMinimumSize(QtCore.QSize(304, 445))
        self.centralwidget = moWidget(studLoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 70, 300, 420))
        self.label.setStyleSheet("border-image: url(:/images/back1.png);\n"
"border-radius: 20px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 80, 280, 401))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.835227 rgba(0, 0, 0, 75));\n"
"border-radius: 20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 80, 280, 390))
        self.label_3.setStyleSheet("background-color:rgba(0,0,0,150);\n"
"border-radius:15px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.studLogin_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.studLogin_pushButton.setGeometry(QtCore.QRect(129, 340, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.studLogin_pushButton.setFont(font)
        self.studLogin_pushButton.setStyleSheet("QPushButton#studLogin_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba();\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#studLogin_pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#studLogin_pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200)\n"
"}\n"
"")
        self.studLogin_pushButton.setObjectName("studLogin_pushButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 100, 141, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgba(255, 255, 255,210);\n"
"")
        self.label_5.setObjectName("label_5")
        self.studToRegister_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.studToRegister_pushButton.setGeometry(QtCore.QRect(130, 410, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.studToRegister_pushButton.setFont(font)
        self.studToRegister_pushButton.setStyleSheet("QPushButton#studToRegister_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,140)\n"
"}\n"
"QPushButton#studToRegister_pushButton:pressed{\n"
"    color: rgba(251, 153, 93, 1);\n"
"}\n"
"")
        self.studToRegister_pushButton.setAutoDefault(False)
        self.studToRegister_pushButton.setDefault(False)
        self.studToRegister_pushButton.setFlat(True)
        self.studToRegister_pushButton.setObjectName("studToRegister_pushButton")
        self.studPass_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.studPass_lineEdit.setGeometry(QtCore.QRect(130, 260, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.studPass_lineEdit.setFont(font)
        self.studPass_lineEdit.setAutoFillBackground(False)
        self.studPass_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.studPass_lineEdit.setText("")
        self.studPass_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.studPass_lineEdit.setObjectName("studPass_lineEdit")
        self.studToForgetEmail_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.studToForgetEmail_pushButton.setGeometry(QtCore.QRect(150, 390, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.studToForgetEmail_pushButton.setFont(font)
        self.studToForgetEmail_pushButton.setStyleSheet("QPushButton#studToForgetEmail_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,140)\n"
"}\n"
"QPushButton#studToForgetEmail_pushButton:pressed{\n"
"    color: rgba(251, 153, 93, 1);\n"
"}\n"
"")
        self.studToForgetEmail_pushButton.setAutoDefault(False)
        self.studToForgetEmail_pushButton.setDefault(False)
        self.studToForgetEmail_pushButton.setFlat(True)
        self.studToForgetEmail_pushButton.setObjectName("studToForgetEmail_pushButton")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(160, 150, 151, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgba(255, 255, 255,210);\n"
"")
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setIndent(-1)
        self.label_6.setObjectName("label_6")
        self.studBackToMain_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.studBackToMain_pushButton.setGeometry(QtCore.QRect(280, 340, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.studBackToMain_pushButton.setFont(font)
        self.studBackToMain_pushButton.setStyleSheet("QPushButton#studBackToMain_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba();\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#studBackToMain_pushButtonn:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#studBackToMain_pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200)\n"
"}\n"
"")
        self.studBackToMain_pushButton.setObjectName("studBackToMain_pushButton")
        self.studEmail_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.studEmail_lineEdit.setGeometry(QtCore.QRect(130, 210, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.studEmail_lineEdit.setFont(font)
        self.studEmail_lineEdit.setAutoFillBackground(False)
        self.studEmail_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.studEmail_lineEdit.setText("")
        self.studEmail_lineEdit.setObjectName("studEmail_lineEdit")
        self.exitProgram_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitProgram_pushButton.setGeometry(QtCore.QRect(340, 80, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.exitProgram_pushButton.setFont(font)
        self.exitProgram_pushButton.setStyleSheet("QPushButton#exitProgram_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba();\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#exitProgram_pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#exitProgram_pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200)\n"
"}\n"
"")
        self.exitProgram_pushButton.setObjectName("exitProgram_pushButton")
        studLoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(studLoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 447, 21))
        self.menubar.setObjectName("menubar")
        studLoginWindow.setMenuBar(self.menubar)

        self.label.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0, color=QtGui.QColor(234, 221, 186, 100)))
        self.label_3.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0, color=QtGui.QColor(105, 118, 132, 100)))
        self.studLogin_pushButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=3, yOffset=3, color=QtGui.QColor(105, 118, 132, 100)))
        self.studBackToMain_pushButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=3, yOffset=3, color=QtGui.QColor(105, 118, 132, 100)))

        self.retranslateUi(studLoginWindow)
        QtCore.QMetaObject.connectSlotsByName(studLoginWindow)

        self.studToRegister_pushButton.clicked.connect(studLoginWindow.toRegister)
        self.studLogin_pushButton.clicked.connect(studLoginWindow.toLogToApp)
        self.studToForgetEmail_pushButton.clicked.connect(studLoginWindow.forgetAcc)
        self.studBackToMain_pushButton.clicked.connect(studLoginWindow.goBack)
        self.exitProgram_pushButton.clicked.connect(studLoginWindow.toExitProg)
        

    def retranslateUi(self, studLoginWindow):
        _translate = QtCore.QCoreApplication.translate
        studLoginWindow.setWindowTitle(_translate("studLoginWindow", "MainWindow"))
        self.label.setText(_translate("studLoginWindow", "TextLabel"))
        self.studLogin_pushButton.setText(_translate("studLoginWindow", "Log In"))
        self.label_5.setText(_translate("studLoginWindow", "Mathguro"))
        self.studToRegister_pushButton.setText(_translate("studLoginWindow", "Don\'t have an Account? Register Here"))
        self.studPass_lineEdit.setPlaceholderText(_translate("studLoginWindow", " Password :"))
        self.studToForgetEmail_pushButton.setText(_translate("studLoginWindow", "Forgot your Email or Password ?"))
        self.label_6.setText(_translate("studLoginWindow", "Student\'s Log In"))
        self.studBackToMain_pushButton.setText(_translate("studLoginWindow", "Back"))
        self.studEmail_lineEdit.setPlaceholderText(_translate("studLoginWindow", " Email :"))
        self.exitProgram_pushButton.setText(_translate("studLoginWindow", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studLoginWindow = QtWidgets.QMainWindow()
    ui = Ui_studLoginWindow()
    ui.setupUi(studLoginWindow)
    studLoginWindow.show()
    sys.exit(app.exec_())
