# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'studTeachButton.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, res

# class that  will change ,self.widget = QtWidgets.QWidget(Form), into moWidget
# this class will used to move the frameless form Window
class moWidget (QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(moWidget, self).__init__(parent)
        self.parent = parent
    def mousePressEvent(self, event):
        if event.button() == QtCore.Qt.LeftButton:
                self.dragPosition = event.globalPos() - self.parent.frameGeometry().topLeft()
                event.accept()
    def mouseMoveEvent(self, event):
        if event.buttons() == QtCore.Qt.LeftButton:
                self.parent.move(event.globalPos() - self.dragPosition)
                event.accept()

class Ui_studTeachWindow(object):
    def setupUi(self, studTeachWindow):
        studTeachWindow.setObjectName("studTeachWindow")
        studTeachWindow.setEnabled(True)
        studTeachWindow.resize(447, 572)
        studTeachWindow.setFixedSize(447, 572)
        # to remove close,minimize,maximize button
        studTeachWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        # to remove the constant background of the app
        studTeachWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(studTeachWindow.sizePolicy().hasHeightForWidth())
        studTeachWindow.setSizePolicy(sizePolicy)
        studTeachWindow.setMinimumSize(QtCore.QSize(302, 385))
        studTeachWindow.setAnimated(True)

        self.centralwidget = moWidget(studTeachWindow)

        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 90, 300, 361))
        self.label.setStyleSheet("border-image: url(:/images/back1.png);\n"
"border-radius: 20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 100, 280, 341))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.835227 rgba(0, 0, 0, 75));\n"
"border-radius: 20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 100, 280, 331))
        self.label_3.setStyleSheet("background-color:rgba(0,0,0,150);\n"
"border-radius:15px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 130, 141, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgba(255, 255, 255,210);\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(170, 180, 121, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgba(255, 255, 255,210);\n"
"")
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setIndent(-1)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(160, 280, 141, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgba(255, 255, 255,210);\n"
"")
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(False)
        self.label_7.setIndent(-1)
        self.label_7.setObjectName("label_7")
        self.stud_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.stud_pushButton.setGeometry(QtCore.QRect(160, 230, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stud_pushButton.setFont(font)
        self.stud_pushButton.setStyleSheet("QPushButton#stud_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba();\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#stud_pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#stud_pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200)\n"
"}\n"
"")
        self.stud_pushButton.setObjectName("stud_pushButton")
        self.teach_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.teach_pushButton.setGeometry(QtCore.QRect(160, 330, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.teach_pushButton.setFont(font)
        self.teach_pushButton.setStyleSheet("QPushButton#teach_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba();\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#teach_pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#teach_pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200)\n"
"}\n"
"")
        self.teach_pushButton.setObjectName("teach_pushButton")
        self.exitProgram_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitProgram_pushButton.setGeometry(QtCore.QRect(340, 100, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.exitProgram_pushButton.setFont(font)
        self.exitProgram_pushButton.setStyleSheet("QPushButton#exitProgram_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba();\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#exitProgram_pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#exitProgram_pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200)\n"
"}\n"
"")
        self.exitProgram_pushButton.setObjectName("exitProgram_pushButton")
        studTeachWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(studTeachWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 447, 21))
        self.menubar.setObjectName("menubar")
        studTeachWindow.setMenuBar(self.menubar)

        self.label.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0, color=QtGui.QColor(234, 221, 186, 100)))
        self.label_3.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0, color=QtGui.QColor(105, 118, 132, 100)))
        self.stud_pushButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=3, yOffset=3, color=QtGui.QColor(105, 118, 132, 100)))
        self.teach_pushButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=3, yOffset=3, color=QtGui.QColor(105, 118, 132, 100)))

        self.retranslateUi(studTeachWindow)
        QtCore.QMetaObject.connectSlotsByName(studTeachWindow)

        self.teach_pushButton.clicked.connect(studTeachWindow.toTeachLogin)
        self.stud_pushButton.clicked.connect(studTeachWindow.toStudLogin)
        self.exitProgram_pushButton.clicked.connect(studTeachWindow.toExitProg)

    def retranslateUi(self, studTeachWindow):
        _translate = QtCore.QCoreApplication.translate
        studTeachWindow.setWindowTitle(_translate("studTeachWindow", "MainWindow"))
        self.label_5.setText(_translate("studTeachWindow", "Mathguro"))
        self.label_6.setText(_translate("studTeachWindow", "Are you a"))
        self.label_7.setText(_translate("studTeachWindow", "or"))
        self.stud_pushButton.setText(_translate("studTeachWindow", "Student"))
        self.teach_pushButton.setText(_translate("studTeachWindow", "Teacher"))
        self.exitProgram_pushButton.setText(_translate("studTeachWindow", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studTeachWindow = QtWidgets.QMainWindow()
    ui = Ui_studTeachWindow()
    ui.setupUi(studTeachWindow)
    studTeachWindow.show()
    sys.exit(app.exec_())
