# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teachLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, res

class moWidget (QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(moWidget, self).__init__(parent)
        self.parent = parent
    def mousePressEvent(self, event):
        if event.button() == QtCore.Qt.LeftButton:
                self.dragPosition = event.globalPos() - self.parent.frameGeometry().topLeft()
                event.accept()
    def mouseMoveEvent(self, event):
        if event.buttons() == QtCore.Qt.LeftButton:
                self.parent.move(event.globalPos() - self.dragPosition)
                event.accept()

class Ui_teachLoginWindow(object):
    def setupUi(self, teachLoginWindow):
        teachLoginWindow.setObjectName("teachLoginWindow")
        teachLoginWindow.resize(447, 572)
        teachLoginWindow.setFixedSize(447, 572)
        # to remove close,minimize,maximize button
        teachLoginWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        # to remove the constant background of the app
        teachLoginWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(teachLoginWindow.sizePolicy().hasHeightForWidth())
        teachLoginWindow.setSizePolicy(sizePolicy)
        self.centralwidget = moWidget(teachLoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 60, 300, 420))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(300, 420))
        self.label.setStyleSheet("border-image: url(:/images/back1.png);\n"
"border-radius: 20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 70, 280, 401))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.835227 rgba(0, 0, 0, 75));\n"
"border-radius: 20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 70, 280, 390))
        self.label_3.setStyleSheet("background-color:rgba(0,0,0,150);\n"
"border-radius:15px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.teachBackToMain_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.teachBackToMain_pushButton.setGeometry(QtCore.QRect(280, 330, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.teachBackToMain_pushButton.setFont(font)
        self.teachBackToMain_pushButton.setStyleSheet("QPushButton#teachBackToMain_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba();\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#teachBackToMain_pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#teachBackToMain_pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200)\n"
"}\n"
"")
        self.teachBackToMain_pushButton.setObjectName("teachBackToMain_pushButton")
        self.teachToForgetEmail_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.teachToForgetEmail_pushButton.setGeometry(QtCore.QRect(150, 380, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.teachToForgetEmail_pushButton.setFont(font)
        self.teachToForgetEmail_pushButton.setStyleSheet("QPushButton#teachToForgetEmail_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,140)\n"
"}\n"
"QPushButton#teachToForgetEmail_pushButton:pressed{\n"
"    color: rgba(251, 153, 93, 1);\n"
"}\n"
"")
        self.teachToForgetEmail_pushButton.setAutoDefault(False)
        self.teachToForgetEmail_pushButton.setDefault(False)
        self.teachToForgetEmail_pushButton.setFlat(True)
        self.teachToForgetEmail_pushButton.setObjectName("teachToForgetEmail_pushButton")
        self.teachEmail_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.teachEmail_lineEdit.setGeometry(QtCore.QRect(130, 200, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.teachEmail_lineEdit.setFont(font)
        self.teachEmail_lineEdit.setAutoFillBackground(False)
        self.teachEmail_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.teachEmail_lineEdit.setText("")
        self.teachEmail_lineEdit.setObjectName("teachEmail_lineEdit")
        self.teachLogin_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.teachLogin_pushButton.setGeometry(QtCore.QRect(129, 330, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.teachLogin_pushButton.setFont(font)
        self.teachLogin_pushButton.setStyleSheet("QPushButton#teachLogin_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba();\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#teachLogin_pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#teachLogin_pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200)\n"
"}\n"
"")
        self.teachLogin_pushButton.setObjectName("teachLogin_pushButton")
        self.teachPass_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.teachPass_lineEdit.setGeometry(QtCore.QRect(130, 250, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.teachPass_lineEdit.setFont(font)
        self.teachPass_lineEdit.setAutoFillBackground(False)
        self.teachPass_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.teachPass_lineEdit.setText("")
        self.teachPass_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.teachPass_lineEdit.setObjectName("teachPass_lineEdit")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(160, 140, 151, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgba(255, 255, 255,210);\n"
"")
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setIndent(-1)
        self.label_6.setObjectName("label_6")
        self.teachToRegister_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.teachToRegister_pushButton.setGeometry(QtCore.QRect(130, 400, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.teachToRegister_pushButton.setFont(font)
        self.teachToRegister_pushButton.setStyleSheet("QPushButton#teachToRegister_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,140)\n"
"}\n"
"QPushButton#teachToRegister_pushButton:pressed{\n"
"    color: rgba(251, 153, 93, 1);\n"
"}\n"
"")
        self.teachToRegister_pushButton.setAutoDefault(False)
        self.teachToRegister_pushButton.setDefault(False)
        self.teachToRegister_pushButton.setFlat(True)
        self.teachToRegister_pushButton.setObjectName("teachToRegister_pushButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 90, 151, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgba(255, 255, 255,210);\n"
"")
        self.label_5.setObjectName("label_5")
        self.exitProgram_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitProgram_pushButton.setGeometry(QtCore.QRect(340, 70, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.exitProgram_pushButton.setFont(font)
        self.exitProgram_pushButton.setStyleSheet("QPushButton#exitProgram_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba();\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#exitProgram_pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#exitProgram_pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200)\n"
"}\n"
"")
        self.exitProgram_pushButton.setObjectName("exitProgram_pushButton")
        teachLoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(teachLoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 447, 21))
        self.menubar.setObjectName("menubar")
        teachLoginWindow.setMenuBar(self.menubar)

        self.label.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0, color=QtGui.QColor(234, 221, 186, 100)))
        self.label_3.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0, color=QtGui.QColor(105, 118, 132, 100)))
        self.teachLogin_pushButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=3, yOffset=3, color=QtGui.QColor(105, 118, 132, 100)))
        self.teachBackToMain_pushButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=3, yOffset=3, color=QtGui.QColor(105, 118, 132, 100)))

        self.retranslateUi(teachLoginWindow)
        QtCore.QMetaObject.connectSlotsByName(teachLoginWindow)

        self.teachToRegister_pushButton.clicked.connect(teachLoginWindow.toRegister) #REGISTER ACCOUNT
        self.teachLogin_pushButton.clicked.connect(teachLoginWindow.toLogToApp)      #LOG IN ACCOUNT 
        self.teachToForgetEmail_pushButton.clicked.connect(teachLoginWindow.forgetAcc) #FORGET ACCOUNT
        self.teachBackToMain_pushButton.clicked.connect(teachLoginWindow.goBack)     #GO TO MAIN
        self.exitProgram_pushButton.clicked.connect(teachLoginWindow.toExitProg)     #TERMINATE APP

    def retranslateUi(self, teachLoginWindow):
        _translate = QtCore.QCoreApplication.translate
        teachLoginWindow.setWindowTitle(_translate("teachLoginWindow", "MainWindow"))
        self.teachBackToMain_pushButton.setText(_translate("teachLoginWindow", "Back"))
        self.teachToForgetEmail_pushButton.setText(_translate("teachLoginWindow", "Forgot your Email or Password ?"))
        self.teachEmail_lineEdit.setPlaceholderText(_translate("teachLoginWindow", " Email :"))
        self.teachLogin_pushButton.setText(_translate("teachLoginWindow", "Log In"))
        self.teachPass_lineEdit.setPlaceholderText(_translate("teachLoginWindow", " Password :"))
        self.label_6.setText(_translate("teachLoginWindow", "Teacher\'s Log In"))
        self.teachToRegister_pushButton.setText(_translate("teachLoginWindow", "Don\'t have an Account? Register Here"))
        self.label_5.setText(_translate("teachLoginWindow", "Mathguro"))
        self.exitProgram_pushButton.setText(_translate("teachLoginWindow", "X"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    teachLoginWindow = QtWidgets.QMainWindow()
    ui = Ui_teachLoginWindow()
    ui.setupUi(teachLoginWindow)
    teachLoginWindow.show()
    sys.exit(app.exec_())
