# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teachRegister.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, res

class moWidget (QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(moWidget, self).__init__(parent)
        self.parent = parent
    def mousePressEvent(self, event):
        if event.button() == QtCore.Qt.LeftButton:
                self.dragPosition = event.globalPos() - self.parent.frameGeometry().topLeft()
                event.accept()
    def mouseMoveEvent(self, event):
        if event.buttons() == QtCore.Qt.LeftButton:
                self.parent.move(event.globalPos() - self.dragPosition)
                event.accept()

class Ui_teachRegisterWindow(object):
    def setupUi(self, teachRegisterWindow):
        teachRegisterWindow.setObjectName("teachRegisterWindow")
        teachRegisterWindow.resize(587, 685)
        teachRegisterWindow.setFixedSize(587, 685)
        # to remove close,minimize,maximize button
        teachRegisterWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        # to remove the constant background of the app
        teachRegisterWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(teachRegisterWindow.sizePolicy().hasHeightForWidth())
        teachRegisterWindow.setSizePolicy(sizePolicy)
        teachRegisterWindow.setMinimumSize(QtCore.QSize(305, 596))
        self.centralwidget = moWidget(teachRegisterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 40, 300, 571))
        self.label.setStyleSheet("border-image: url(:/images/back1.png);\n"
"border-radius: 20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(159, 50, 281, 551))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.835227 rgba(0, 0, 0, 75));\n"
"border-radius: 20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 90, 280, 501))
        self.label_3.setStyleSheet("background-color:rgba(0,0,0,150);\n"
"border-radius:15px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(230, 70, 141, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgba(255, 255, 255,210);\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(220, 120, 161, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgba(255, 255, 255,210);\n"
"")
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setIndent(-1)
        self.label_6.setObjectName("label_6")
        self.teachBackToMain_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.teachBackToMain_pushButton.setGeometry(QtCore.QRect(350, 480, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.teachBackToMain_pushButton.setFont(font)
        self.teachBackToMain_pushButton.setStyleSheet("QPushButton#teachBackToMain_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba();\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#teachBackToMain_pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#teachBackToMain_pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200)\n"
"}\n"
"")
        self.teachBackToMain_pushButton.setObjectName("teachBackToMain_pushButton")
        self.teachEmail_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.teachEmail_lineEdit.setGeometry(QtCore.QRect(200, 360, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.teachEmail_lineEdit.setFont(font)
        self.teachEmail_lineEdit.setAutoFillBackground(False)
        self.teachEmail_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.teachEmail_lineEdit.setText("")
        self.teachEmail_lineEdit.setObjectName("teachEmail_lineEdit")
        self.teachFirstName_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.teachFirstName_lineEdit.setGeometry(QtCore.QRect(200, 160, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.teachFirstName_lineEdit.setFont(font)
        self.teachFirstName_lineEdit.setAutoFillBackground(False)
        self.teachFirstName_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.teachFirstName_lineEdit.setText("")
        self.teachFirstName_lineEdit.setObjectName("teachFirstName_lineEdit")
        self.teachId_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.teachId_lineEdit.setGeometry(QtCore.QRect(200, 260, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.teachId_lineEdit.setFont(font)
        self.teachId_lineEdit.setAutoFillBackground(False)
        self.teachId_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.teachId_lineEdit.setText("")
        self.teachId_lineEdit.setObjectName("teachId_lineEdit")
        self.teachLastName_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.teachLastName_lineEdit.setGeometry(QtCore.QRect(200, 210, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.teachLastName_lineEdit.setFont(font)
        self.teachLastName_lineEdit.setAutoFillBackground(False)
        self.teachLastName_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.teachLastName_lineEdit.setText("")
        self.teachLastName_lineEdit.setObjectName("teachLastName_lineEdit")
        self.teachMiddleInit_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.teachMiddleInit_lineEdit.setGeometry(QtCore.QRect(340, 160, 61, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.teachMiddleInit_lineEdit.setFont(font)
        self.teachMiddleInit_lineEdit.setAutoFillBackground(False)
        self.teachMiddleInit_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.teachMiddleInit_lineEdit.setText("")
        self.teachMiddleInit_lineEdit.setObjectName("teachMiddleInit_lineEdit")
        self.teachPass_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.teachPass_lineEdit.setGeometry(QtCore.QRect(200, 410, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.teachPass_lineEdit.setFont(font)
        self.teachPass_lineEdit.setAutoFillBackground(False)
        self.teachPass_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.teachPass_lineEdit.setText("")
        self.teachPass_lineEdit.setObjectName("teachPass_lineEdit")
        self.teachSchool_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.teachSchool_lineEdit.setGeometry(QtCore.QRect(200, 310, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.teachSchool_lineEdit.setFont(font)
        self.teachSchool_lineEdit.setAutoFillBackground(False)
        self.teachSchool_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.teachSchool_lineEdit.setText("")
        self.teachSchool_lineEdit.setObjectName("teachSchool_lineEdit")
        self.teachRegister_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.teachRegister_pushButton.setGeometry(QtCore.QRect(200, 480, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.teachRegister_pushButton.setFont(font)
        self.teachRegister_pushButton.setStyleSheet("QPushButton#teachRegister_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba();\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#teachRegister_pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#teachRegister_pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200)\n"
"}\n"
"")
        self.teachRegister_pushButton.setObjectName("teachRegister_pushButton")
        self.teachToLogIn_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.teachToLogIn_pushButton.setGeometry(QtCore.QRect(210, 530, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.teachToLogIn_pushButton.setFont(font)
        self.teachToLogIn_pushButton.setStyleSheet("QPushButton#teachToLogIn_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,140)\n"
"}\n"
"QPushButton#teachToLogIn_pushButton:pressed{\n"
"    color: rgba(251, 153, 93, 1);\n"
"}\n"
"")
        self.teachToLogIn_pushButton.setAutoDefault(False)
        self.teachToLogIn_pushButton.setDefault(False)
        self.teachToLogIn_pushButton.setFlat(True)
        self.teachToLogIn_pushButton.setObjectName("teachToLogIn_pushButton")
        self.exitProgram_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitProgram_pushButton.setGeometry(QtCore.QRect(410, 50, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.exitProgram_pushButton.setFont(font)
        self.exitProgram_pushButton.setStyleSheet("QPushButton#exitProgram_pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba();\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#exitProgram_pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#exitProgram_pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200)\n"
"}\n"
"")
        self.exitProgram_pushButton.setObjectName("exitProgram_pushButton")
        teachRegisterWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(teachRegisterWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 587, 21))
        self.menubar.setObjectName("menubar")
        teachRegisterWindow.setMenuBar(self.menubar)

        self.retranslateUi(teachRegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(teachRegisterWindow)

        self.teachRegister_pushButton.clicked.connect(teachRegisterWindow.toRegisterDb)
        self.teachToLogIn_pushButton.clicked.connect(teachRegisterWindow.goBack)
        self.teachBackToMain_pushButton.clicked.connect(teachRegisterWindow.goBack)
        self.exitProgram_pushButton.clicked.connect(teachRegisterWindow.toExitProg)


    def retranslateUi(self, teachRegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        teachRegisterWindow.setWindowTitle(_translate("teachRegisterWindow", "MainWindow"))
        self.label_5.setText(_translate("teachRegisterWindow", "Mathguro"))
        self.label_6.setText(_translate("teachRegisterWindow", "Teacher\'s Register"))
        self.teachBackToMain_pushButton.setText(_translate("teachRegisterWindow", "Back"))
        self.teachEmail_lineEdit.setPlaceholderText(_translate("teachRegisterWindow", " Email:"))
        self.teachFirstName_lineEdit.setPlaceholderText(_translate("teachRegisterWindow", "First Name:"))
        self.teachId_lineEdit.setPlaceholderText(_translate("teachRegisterWindow", " Teacher\'s School I.D.:"))
        self.teachLastName_lineEdit.setPlaceholderText(_translate("teachRegisterWindow", "Last Name:"))
        self.teachMiddleInit_lineEdit.setPlaceholderText(_translate("teachRegisterWindow", "M.I:"))
        self.teachPass_lineEdit.setPlaceholderText(_translate("teachRegisterWindow", " Password:"))
        self.teachSchool_lineEdit.setPlaceholderText(_translate("teachRegisterWindow", " School:"))
        self.teachRegister_pushButton.setText(_translate("teachRegisterWindow", "Register"))
        self.teachToLogIn_pushButton.setText(_translate("teachRegisterWindow", "Already have an Account? Log In Here"))
        self.exitProgram_pushButton.setText(_translate("teachRegisterWindow", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    teachRegisterWindow = QtWidgets.QMainWindow()
    ui = Ui_teachRegisterWindow()
    ui.setupUi(teachRegisterWindow)
    teachRegisterWindow.show()
    sys.exit(app.exec_())
