# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warningToLogOut.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_logoutDialog(object):
    def setupUi(self, logoutDialog):
        logoutDialog.setObjectName("logoutDialog")
        logoutDialog.resize(498, 181)
        logoutDialog.setStyleSheet("*{\n"
"border: none;\n"
"background-color: transparent;\n"
"background: transparent;\n"
"padding: 0;\n"
"margin: 0;\n"
"color: #fff\n"
"}\n"
"#logoutDialog{\n"
"    background-color: rgb(57, 74, 97);\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(logoutDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(logoutDialog)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_3 = QtWidgets.QWidget(self.page)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setStyleSheet("background-color: rgb(12, 127, 119);\n"
"border-radius: 5px;")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.textEdit = QtWidgets.QTextEdit(self.widget_5)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_7.addWidget(self.textEdit)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_6.setContentsMargins(0, 6, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_6 = QtWidgets.QWidget(self.widget_4)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.yes_pushButton = QtWidgets.QPushButton(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.yes_pushButton.setFont(font)
        self.yes_pushButton.setStyleSheet("QPushButton#yes_pushButton{\n"
"    background-color: rgb(63, 162, 40);\n"
"    padding:5px 30px 5px 30px ;\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#yes_pushButton:hover{\n"
"    background-color: rgb(64, 204, 68);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#yes_pushButton:pressed{\n"
"    background-color: rgb(46, 97, 37);\n"
"    border-radius: 5px;\n"
"}")
        self.yes_pushButton.setObjectName("yes_pushButton")
        self.horizontalLayout.addWidget(self.yes_pushButton, 0, QtCore.Qt.AlignHCenter)
        self.no_pushButton = QtWidgets.QPushButton(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.no_pushButton.setFont(font)
        self.no_pushButton.setStyleSheet("QPushButton#no_pushButton{\n"
"    background-color: rgb(220, 68, 68);\n"
"    padding:5px 30px 5px 30px ;\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#no_pushButton:hover{\n"
"    background-color: rgb(182, 0, 0);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#no_pushButton:pressed{\n"
"    background-color: rgb(132, 0, 0);\n"
"    border-radius: 5px;\n"
"}")
        self.no_pushButton.setObjectName("no_pushButton")
        self.horizontalLayout.addWidget(self.no_pushButton, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_6.addWidget(self.widget_6)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.verticalLayout_5.addWidget(self.widget_3)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_7 = QtWidgets.QWidget(self.page_2)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_8 = QtWidgets.QWidget(self.widget_7)
        self.widget_8.setStyleSheet("background-color: rgb(12, 127, 119);\n"
"border-radius: 5px;")
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget_8)
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_9.addWidget(self.textEdit_2)
        self.verticalLayout_8.addWidget(self.widget_8)
        self.widget_9 = QtWidgets.QWidget(self.widget_7)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_10.setContentsMargins(0, 6, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_10 = QtWidgets.QWidget(self.widget_9)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.yes_pushButton_2 = QtWidgets.QPushButton(self.widget_10)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.yes_pushButton_2.setFont(font)
        self.yes_pushButton_2.setStyleSheet("QPushButton#yes_pushButton_2{\n"
"    background-color: rgb(63, 162, 40);\n"
"    padding:5px 30px 5px 30px ;\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#yes_pushButton_2:hover{\n"
"    background-color: rgb(64, 204, 68);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#yes_pushButton_2:pressed{\n"
"    background-color: rgb(46, 97, 37);\n"
"    border-radius: 5px;\n"
"}")
        self.yes_pushButton_2.setObjectName("yes_pushButton_2")
        self.horizontalLayout_2.addWidget(self.yes_pushButton_2, 0, QtCore.Qt.AlignHCenter)
        self.no_pushButton_2 = QtWidgets.QPushButton(self.widget_10)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.no_pushButton_2.setFont(font)
        self.no_pushButton_2.setStyleSheet("QPushButton#no_pushButton_2{\n"
"    background-color: rgb(220, 68, 68);\n"
"    padding:5px 30px 5px 30px ;\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#no_pushButton_2:hover{\n"
"    background-color: rgb(182, 0, 0);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#no_pushButton_2:pressed{\n"
"    background-color: rgb(132, 0, 0);\n"
"    border-radius: 5px;\n"
"}")
        self.no_pushButton_2.setObjectName("no_pushButton_2")
        self.horizontalLayout_2.addWidget(self.no_pushButton_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addWidget(self.widget_10)
        self.verticalLayout_8.addWidget(self.widget_9)
        self.verticalLayout_11.addWidget(self.widget_7)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(logoutDialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(logoutDialog)

    def retranslateUi(self, logoutDialog):
        _translate = QtCore.QCoreApplication.translate
        logoutDialog.setWindowTitle(_translate("logoutDialog", "Dialog"))
        self.textEdit.setHtml(_translate("logoutDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Are you sure you want to Log out?</span></p></body></html>"))
        self.yes_pushButton.setText(_translate("logoutDialog", "Yes"))
        self.no_pushButton.setText(_translate("logoutDialog", "No"))
        self.textEdit_2.setHtml(_translate("logoutDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Are you sure you want to Log out?</span></p></body></html>"))
        self.yes_pushButton_2.setText(_translate("logoutDialog", "Yes"))
        self.no_pushButton_2.setText(_translate("logoutDialog", "No"))
import res, sys


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    logoutDialog = QtWidgets.QDialog()
    ui = Ui_logoutDialog()
    ui.setupUi(logoutDialog)
    logoutDialog.show()
    sys.exit(app.exec_())
