# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data\adminLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_adminWindow(object):
    def setupUi(self, adminWindow):
        adminWindow.setObjectName("adminWindow")
        adminWindow.resize(294, 437)
        self.centralwidget = QtWidgets.QWidget(adminWindow)
        self.centralwidget.setStyleSheet("*{\n"
"border: none;\n"
"background-color: transparent;\n"
"background: transparent;\n"
"padding: 0;\n"
"margin: 0;\n"
"color: #fff;\n"
"}\n"
"#frame{\n"
"border-image: url(:/images/back1.png);\n"
"}\n"
"#frame_4{\n"
"background-color:rgba(0,0,0,175);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"#label, #label_2, #label_3, #label_4{\n"
"color: rgba(255, 255, 255,210);\n"
"}\n"
"QPushButton#closeButton,#loginAdminButton,#backButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba();\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#closeButton:hover, #loginAdminButton:hover, #backButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:0.989, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#closeButton:pressed, #loginAdminButton:pressed, #backButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200)\n"
"}\n"
"#adminEmail_lineEdit, #adminPass_lineEdit{\n"
"background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.frame_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.closeButton = QtWidgets.QPushButton(self.widget_3)
        self.closeButton.setStyleSheet("")
        self.closeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon)
        self.closeButton.setIconSize(QtCore.QSize(25, 25))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.verticalLayout_2.addWidget(self.widget_3, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.widget_7 = QtWidgets.QWidget(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(1)
        self.widget_7.setFont(font)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(20)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_10.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.widget_7, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.widget_6 = QtWidgets.QWidget(self.frame_2)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_6.setContentsMargins(40, 0, 40, 0)
        self.verticalLayout_6.setSpacing(15)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.adminEmail_lineEdit = QtWidgets.QLineEdit(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.adminEmail_lineEdit.setFont(font)
        self.adminEmail_lineEdit.setStyleSheet("")
        self.adminEmail_lineEdit.setText("")
        self.adminEmail_lineEdit.setObjectName("adminEmail_lineEdit")
        self.verticalLayout_6.addWidget(self.adminEmail_lineEdit)
        self.adminPass_lineEdit = QtWidgets.QLineEdit(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.adminPass_lineEdit.setFont(font)
        self.adminPass_lineEdit.setStyleSheet("")
        self.adminPass_lineEdit.setText("")
        self.adminPass_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.adminPass_lineEdit.setObjectName("adminPass_lineEdit")
        self.verticalLayout_6.addWidget(self.adminPass_lineEdit)
        self.warning_Widget = QtWidgets.QWidget(self.widget_6)
        self.warning_Widget.setStyleSheet("")
        self.warning_Widget.setObjectName("warning_Widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.warning_Widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.warningPages = QtWidgets.QStackedWidget(self.warning_Widget)
        self.warningPages.setObjectName("warningPages")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.warningPages.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.warningPages.addWidget(self.page_2)
        self.verticalLayout_4.addWidget(self.warningPages)
        self.verticalLayout_6.addWidget(self.warning_Widget, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_2.addWidget(self.widget_6)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_5 = QtWidgets.QWidget(self.frame_3)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.widget_5)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.loginAdminButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loginAdminButton.setFont(font)
        self.loginAdminButton.setStyleSheet("    padding: 10px 40px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;")
        self.loginAdminButton.setIconSize(QtCore.QSize(12, 12))
        self.loginAdminButton.setAutoDefault(False)
        self.loginAdminButton.setDefault(False)
        self.loginAdminButton.setFlat(False)
        self.loginAdminButton.setObjectName("loginAdminButton")
        self.horizontalLayout_3.addWidget(self.loginAdminButton)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_4 = QtWidgets.QWidget(self.widget_5)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.backButton = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backButton.sizePolicy().hasHeightForWidth())
        self.backButton.setSizePolicy(sizePolicy)
        self.backButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("    padding: 10px 10px;\n"
"")
        self.backButton.setIconSize(QtCore.QSize(16, 16))
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_4.addWidget(self.backButton)
        self.horizontalLayout.addWidget(self.widget_4)
        self.verticalLayout_3.addWidget(self.widget_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout_8.addWidget(self.frame_4)
        self.verticalLayout_11.addWidget(self.frame)
        adminWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(adminWindow)
        self.warningPages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(adminWindow)

    def retranslateUi(self, adminWindow):
        _translate = QtCore.QCoreApplication.translate
        adminWindow.setWindowTitle(_translate("adminWindow", "MainWindow"))
        self.label.setText(_translate("adminWindow", "PreCalGuro"))
        self.label_4.setText(_translate("adminWindow", "Admin Log In"))
        self.adminEmail_lineEdit.setPlaceholderText(_translate("adminWindow", "Email:"))
        self.adminPass_lineEdit.setPlaceholderText(_translate("adminWindow", "Password:"))
        self.label_5.setText(_translate("adminWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#ff9393;\">Incorrect</span></p><p align=\"center\"><span style=\" font-size:10pt; color:#ff9393;\">Email or Password</span></p></body></html>"))
        self.label_6.setText(_translate("adminWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ff9393;\">User Doesn\'t Exist</span></p></body></html>"))
        self.loginAdminButton.setText(_translate("adminWindow", "Log In"))
        self.backButton.setText(_translate("adminWindow", "Back"))
import sys
sys.path.append("assets")
import res
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    adminWindow = QtWidgets.QMainWindow()
    ui = Ui_adminWindow()
    ui.setupUi(adminWindow)
    adminWindow.show()
    sys.exit(app.exec_())
