# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data\loadingScreen1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loadingScreenWindow(object):
    def setupUi(self, loadingScreenWindow):
        loadingScreenWindow.setObjectName("loadingScreenWindow")
        loadingScreenWindow.resize(455, 311)
        self.centralwidget = QtWidgets.QWidget(loadingScreenWindow)
        self.centralwidget.setStyleSheet("border-image: url(:/images/load1.png);")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 20, 131, 121))
        self.label.setStyleSheet("border-image: url(:/images/logo.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(30, 200, 401, 31))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(78, 93, 100);\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(162, 202, 214);\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        loadingScreenWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(loadingScreenWindow)
        QtCore.QMetaObject.connectSlotsByName(loadingScreenWindow)

    def retranslateUi(self, loadingScreenWindow):
        _translate = QtCore.QCoreApplication.translate
        loadingScreenWindow.setWindowTitle(_translate("loadingScreenWindow", "MainWindow"))
import sys
from data import res

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loadingScreenWindow = QtWidgets.QMainWindow()
    ui = Ui_loadingScreenWindow()
    ui.setupUi(loadingScreenWindow)
    loadingScreenWindow.show()
    sys.exit(app.exec_())
