# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data\processScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_processWindow(object):
    def setupUi(self, processWindow):
        processWindow.setObjectName("processWindow")
        processWindow.resize(455, 311)
        processWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(processWindow)
        self.centralwidget.setStyleSheet("*{\n"
"border: none;\n"
"background-color: transparent;\n"
"background: transparent;\n"
"padding: 0;\n"
"margin: 0;\n"
"color: #fff;\n"
"}\n"
"#widget{\n"
"border-image: url(:/images/load1.png);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, 9, -1, 9)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        self.label.setStyleSheet("border-image: url(:/images/logo.png);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.widget_2, 0, QtCore.Qt.AlignHCenter)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setContentsMargins(0, 20, 0, 20)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.progressBar = QtWidgets.QProgressBar(self.widget_3)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 30))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(0, 255, 0);\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        self.verticalLayout_2.addWidget(self.widget_3, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.widget)
        processWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(processWindow)
        QtCore.QMetaObject.connectSlotsByName(processWindow)

    def retranslateUi(self, processWindow):
        _translate = QtCore.QCoreApplication.translate
        processWindow.setWindowTitle(_translate("processWindow", "MainWindow"))
        self.label_2.setText(_translate("processWindow", "Processing Calculations"))
import sys
sys.path.append("assets")
import res

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    processWindow = QtWidgets.QMainWindow()
    ui = Ui_processWindow()
    ui.setupUi(processWindow)
    processWindow.show()
    sys.exit(app.exec_())
